server {
    # Unprivileged port
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Handle Hugo's pretty URLs
    location / {
        try_files $uri $uri/ =404;
    }

    # Wire up Hugo's custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
